Repository zavolanlab/merge_kallisto, pull requests merged in 2020-06, with the labels that each got.

#1 First version with big docker image
  .github/workflows/build-image.yml
  Dockerfile
  R/merge_kallisto.R
  README.md
Labels: enhancement

#3 Improvements in merge_kallisto.R script
  R/merge_kallisto.R
Labels: enhancement

#4 Update versions in Dockerfile
  Dockerfile
Labels: enhancement

#5 Update Dockerfile
  Dockerfile
Labels: bug

#9 Removed busparse package
  R/merge_kallisto.R
Labels: enhancement

#10 Fix dockerfile and reduce docker image size
  Dockerfile
  README.md
Labels: bug, enhancement
